# Generated by Django 5.1.5 on 2025-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('pagesCount', models.BigIntegerField()),
                ('ISBN', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birthday', models.BigIntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('books', models.ManyToManyField(to='base.book')),
            ],
        ),
    ]
